name: Déploiement Symfony

on:
  push:
    branches:
      - main

jobs:
  deployer:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: SSH
        uses: easingthemes/ssh-deploy@v2.1.4
        with:
          ssh_key: ${{ secrets.SSH_KEY }}
          host: ${{ secrets.APP_HOST }}
          username: ${{ secrets.APP_USER }}
          #port: ${{ secrets.APP_PORT }}
          
          # commandes à exécuter sur le serveur
          commands:
            - export PATH="/opt/php8.2/bin:$PATH"
            - cd ${{ secrets.APP_PATH }}
            - composer install --no-dev --optimize-autoloader
            #- yarn install --production
            - cp -R public/build/ .
            - php bin/console doctrine:migrations:migrate --no-interaction
            - php bin/console cache:clear
            - sudo service nginx restart
